# Generated by Django 5.2.7 on 2026-01-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='lib_address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
