# Generated by Django 5.2.8 on 2025-12-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
