# Generated by Django 5.2.7 on 2026-01-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_book_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
