# Generated by Django 5.2.7 on 2026-01-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_book_copies_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='copies',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
